# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

# User defined variables are also injected as environment variables
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables#environment-variables
#variables:
  #ANSIBLE_VERBOSITY: 3

jobs:

- job: Mac1014
  # vanilla Ansible is really slow
  timeoutInMinutes: 120
  steps:
  - template: azure-pipelines-steps.yml
  pool:
    vmImage: macOS-10.14
  strategy:
    matrix:
      Mito_27:
        python.version: '2.7'
        tox.env: py27-mode_mitogen
      Mito_36:
        python.version: '3.6'
        tox.env: py36-mode_mitogen
      Mito_39:
        python.version: '3.9'
        tox.env: py39-mode_mitogen

      # TODO: test python3, python3 tests are broken
      Loc_27_210:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible2.10
      Loc_27_3:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible3
      Loc_27_4:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible4

      # NOTE: this hangs when ran in Ubuntu 18.04
      Van_27_210:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible2.10
        STRATEGY: linear
        ANSIBLE_SKIP_TAGS: resource_intensive
      Van_27_3:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible3
        STRATEGY: linear
        ANSIBLE_SKIP_TAGS: resource_intensive
      Van_27_4:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible4
        STRATEGY: linear
        ANSIBLE_SKIP_TAGS: resource_intensive

- job: Mac1015
  # vanilla Ansible is really slow
  timeoutInMinutes: 120
  steps:
  - template: azure-pipelines-steps.yml
  pool:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    vmImage: macOS-10.15
  strategy:
    matrix:
      Mito_27:
        python.version: '2.7'
        tox.env: py27-mode_mitogen
      Mito_36:
        python.version: '3.6'
        tox.env: py36-mode_mitogen
      Mito_39:
        python.version: '3.9'
        tox.env: py39-mode_mitogen

        # TODO: test python3, python3 tests are broken
      Loc_27_210:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible2.10
      Loc_27_3:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible3
      Loc_27_4:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible4

      # NOTE: this hangs when ran in Ubuntu 18.04
      Van_27_210:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible2.10
        STRATEGY: linear
        ANSIBLE_SKIP_TAGS: resource_intensive
      Van_27_3:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible3
        STRATEGY: linear
        ANSIBLE_SKIP_TAGS: resource_intensive
      Van_27_4:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible4
        STRATEGY: linear
        ANSIBLE_SKIP_TAGS: resource_intensive

- job: Mac11
  # vanilla Ansible is really slow
  timeoutInMinutes: 120
  steps:
  - template: azure-pipelines-steps.yml
  pool:
    vmImage: macOS-11
  strategy:
    matrix:
      Mito_39:
        python.version: '3.9'
        tox.env: py39-mode_mitogen

      # TODO: test python3, python3 tests are broken
      Loc_39_210:
        python.version: '3.9'
        tox.env: py39-mode_localhost-ansible2.10
      Loc_39_3:
        python.version: '3.9'
        tox.env: py39-mode_localhost-ansible3
      Loc_39_4:
        python.version: '3.9'
        tox.env: py39-mode_localhost-ansible4

      # NOTE: this hangs when ran in Ubuntu 18.04
      Van_39_210:
        python.version: '3.9'
        tox.env: py39-mode_localhost-ansible2.10
        STRATEGY: linear
        ANSIBLE_SKIP_TAGS: resource_intensive
      Van_39_3:
        python.version: '3.9'
        tox.env: py39-mode_localhost-ansible3
        STRATEGY: linear
        ANSIBLE_SKIP_TAGS: resource_intensive
      Van_39_4:
        python.version: '3.9'
        tox.env: py39-mode_localhost-ansible4
        STRATEGY: linear
        ANSIBLE_SKIP_TAGS: resource_intensive
